An unexpected error occurred: mat1 and mat2 shapes cannot be multiplied (1x301 and 1x64)
Traceback:
Traceback (most recent call last):
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/main.py", line 30, in main
    trainer.train(num_episodes=config['num_episodes'])
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/trainers/ppo_trainer.py", line 153, in train
    alice_action, alice_log_prob, alice_value = self.ppo_trainer.act(state_tensor, 'alice')
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/trainers/ppo_trainer.py", line 96, in act
    dist, value = net(state)
                  ^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/Documents/GitHub/collaborative-stegosystem/src/trainers/ppo_trainer.py", line 37, in forward
    return self.actor(state), self.critic(state)
           ^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chansmi/miniconda3/envs/collaborative-stegosystem/lib/python3.12/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x301 and 1x64)