



Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:21<00:00,  5.44s/it]
WARNING:root:The `device_map` argument is not provided. We will override the device_map argument. to set the entire model on the current device. If you want to set the model on multiple devices, please provide a custom `device_map` argument.



Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:23<00:00,  5.91s/it]
WARNING:root:The `device_map` argument is not provided. We will override the device_map argument. to set the entire model on the current device. If you want to set the model on multiple devices, please provide a custom `device_map` argument.



Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:24<00:00,  6.05s/it]
WARNING:root:The `device_map` argument is not provided. We will override the device_map argument. to set the entire model on the current device. If you want to set the model on multiple devices, please provide a custom `device_map` argument.
WARNING:accelerate.utils.other:Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
/usr/local/lib/python3.10/dist-packages/trl/trainer/ppo_trainer.py:266: UserWarning: No dataset is provided. Make sure to set config.batch_size to the correct value before training.
  warnings.warn(
Training Progress:   0%|                                                                                                     | 0/10 [00:00<?, ?it/s]
An error occurred during training: 'num_conversations_per_day'